services:
  mysql:
    image: mysql
    ports:
      - "23306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ry
      MYSQL_USER: ruoyi
      MYSQL_PASSWORD: ruoyi123456
    volumes:
      - ./mysql:/var/lib/mysql
      - ./ruoyi/mysql:/docker-entrypoint-initdb.d

  redis:
    image: redis
    ports:
      - "6379"
    restart: always
  
  ruoyi-admin:
    image: hwjdk:21-zh
    ports:
      - "28080:8080"
    restart: always
    volumes:
      - ./ruoyi/java:/jars
      - ./ruoyi/files:/var/ruoyi/files
    command: ["-Xmx1024m", "-jar", "/jars/ruoyi-admin.jar"]

  ruoyi-vue3:
    image: nginx
    ports:
      - "22080:80"
    restart: always
    volumes:
      - ./ruoyi/nginx-conf.d:/etc/nginx/conf.d
      - ./ruoyi/ui-vue3:/usr/share/nginx/html
      - ./ruoyi/files:/usr/share/nginx/html/profile

  workwx:
    image: hwjdk:21-zh
    restart: always
    volumes:
      - ./workwx/java:/jars
    command: ["-jar", "/jars/workwx-0.0.1-SNAPSHOT.jar"]
